image:
  name: galacticfog/docker-yarn-debian:8.11.3

stages:
  - build
  - test
  - deploy

build:
  stage: build
  allow_failure: false
  script:
   - apt-get install zip unzip
   - npm install -g pkg 
   - ./build.sh
