image:
  name: galacticfog/docker-yarn-debian:8.11.3

stages:
  - build
  - test
  - deploy

build-cli:
  stage: build
  allow_failure: false
  script:
    - npm install -g pkg 
    - VERSION=$(<package.json jq -r '.version')
    - echo "[Info][FOG CLI Version][${VERSION}]"
    - echo "[Info][CI_COMMIT_SHA][$CI_COMMIT_SHA]"
    - ./build-cli.sh

build-image:
  stage: build
  allow_failure: false
  script:
    - apt-get install zip unzip
    - ls -la ./target
    - ./build-image.sh