image:
  name: galacticfog/docker-yarn-debian:8.11.3

stages:
  - build-cli
  - build-image
  - test
  - deploy

services:
  - docker:dind

build-cli:
  stage: build-cli
  allow_failure: false
  script:
    - echo ${CI_BUILD_TAG} ${CI_BUILD_REF_NAME} #npm install -g pkg 
    - echo ${GF_DOCKER_PWD} | docker login --username ${GF_DOCKER_USER} --password-stdin
    - VERSION=$(<package.json jq -r '.version')
    - echo "[Info][FOG CLI Version][${VERSION}]"
    - echo "[Info][CI_COMMIT_SHA][$CI_COMMIT_SHA]"
    - ./build-cli.sh
  artifacts:
    paths:
    - "./target/*/fog"

build-image:
  stage: build-image
  allow_failure: false
  dependencies: 
    - build-cli
  script:
    - apt-get install zip unzip
    - ls -la ./target
    - VERSION=$(<package.json jq -r '.version')
    - echo "[Info][FOG CLI Version][${VERSION}]"
    - echo "[Info][CI_COMMIT_SHA][$CI_COMMIT_SHA]"
    - echo ${GF_DOCKER_PWD} | docker login --username ${GF_DOCKER_USER} --password-stdin
    - ./build-image.sh "${VERSION} $CI_COMMIT_SHA"
