image:
  name: galacticfog/docker-yarn-debian:8.11.3

stages:
  - build
  - test
  - deploy

build:
  stage: build
  allow_failure: false
  script:
   - apt-get install zip unzip
   - npm install -g pkg 
   - VERSION=$(<package.json jq -r '.version')
   - echo "[Info][FOG CLI Version][${VERSION}]"
   - ./build.sh
   - ls ./target
   - ls ./target/alpine
