image:
  name: galacticfog/docker-yarn-debian:8.11.3

stages:
  - build
  - test
  - deploy
  - publish

services:
  - docker:dind
  
.dependency_common: &dependency_common
  artifacts:
    paths:
    - .ci/
    name: ${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}_ci_flags"

build:
  <<: *dependency_common
  stage: build
  allow_failure: false
  before_script:
  - echo "Install Build Dependencies ..."
  - npm install -g pkg
  - echo "Docker Login ..."
  - echo ${GF_DOCKER_PWD} | docker login --username ${GF_DOCKER_USER} --password-stdin
  script:
    - VERSION=$(<package.json jq -r '.version')
    - echo "Build CLI ${VERSION} ..."
    - ./build-cli.sh
    - echo "Build and publish docker image with CLI"
    - ./build-image.sh "${VERSION} ${CI_COMMIT_SHA:0:8}"
    - echo "Mark ${CI_JOB_NAME} as success ..." 
    - .ci/dependency success
  artifacts:
    paths:
    - "./target/*/fog"
    name: "${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}_cli_binaries"

github-publish:
  <<: *dependency_common
  before_script:
  - .ci/dependency require build-cli build-image
  stage: publish
  script: 
    - git remote remove github || true
    - git remote add github https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_ORG}/${GITHUB_REPO}.git
    - |
      if [ -z ${CI_BUILD_TAG} ]; then 
         git push github HEAD:$CI_BUILD_REF_NAME
      else 
         git push -f github $CI_BUILD_TAG
      fi
  when: manual

